package com.akaiyuki.partyphile.passportapp.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.akaiyuki.partyphile.passportapp.dao.PAppSettings;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PAPP_SETTINGS".
*/
public class PAppSettingsDao extends AbstractDao<PAppSettings, Long> {

    public static final String TABLENAME = "PAPP_SETTINGS";

    /**
     * Properties of entity PAppSettings.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Is_secure = new Property(1, Integer.class, "is_secure", false, "IS_SECURE");
        public final static Property Adhoc_base_path = new Property(2, String.class, "adhoc_base_path", false, "ADHOC_BASE_PATH");
        public final static Property Test_base_path = new Property(3, String.class, "test_base_path", false, "TEST_BASE_PATH");
        public final static Property Staging_base_path = new Property(4, String.class, "staging_base_path", false, "STAGING_BASE_PATH");
        public final static Property Prod_base_path = new Property(5, String.class, "prod_base_path", false, "PROD_BASE_PATH");
        public final static Property Api_resource_path = new Property(6, String.class, "api_resource_path", false, "API_RESOURCE_PATH");
        public final static Property Active_path = new Property(7, Integer.class, "active_path", false, "ACTIVE_PATH");
        public final static Property Is_app_active = new Property(8, Integer.class, "is_app_active", false, "IS_APP_ACTIVE");
        public final static Property Is_app_needs_update = new Property(9, Integer.class, "is_app_needs_update", false, "IS_APP_NEEDS_UPDATE");
        public final static Property Is_paypal_active = new Property(10, Integer.class, "is_paypal_active", false, "IS_PAYPAL_ACTIVE");
        public final static Property Is_dragonpay_active = new Property(11, Integer.class, "is_dragonpay_active", false, "IS_DRAGONPAY_ACTIVE");
        public final static Property Is_globelabs_active = new Property(12, Integer.class, "is_globelabs_active", false, "IS_GLOBELABS_ACTIVE");
        public final static Property Will_force_close_when_cancelled_updates = new Property(13, Integer.class, "will_force_close_when_cancelled_updates", false, "WILL_FORCE_CLOSE_WHEN_CANCELLED_UPDATES");
        public final static Property Allow_ads = new Property(14, Integer.class, "allow_ads", false, "ALLOW_ADS");
        public final static Property Event_main_pics_path = new Property(15, String.class, "event_main_pics_path", false, "EVENT_MAIN_PICS_PATH");
        public final static Property Event_banner_pics_path = new Property(16, String.class, "event_banner_pics_path", false, "EVENT_BANNER_PICS_PATH");
        public final static Property Venue_main_pics_path = new Property(17, String.class, "venue_main_pics_path", false, "VENUE_MAIN_PICS_PATH");
        public final static Property Venue_banner_pics_path = new Property(18, String.class, "venue_banner_pics_path", false, "VENUE_BANNER_PICS_PATH");
        public final static Property Booth_map_path = new Property(19, String.class, "booth_map_path", false, "BOOTH_MAP_PATH");
        public final static Property Pass_pic_path = new Property(20, String.class, "pass_pic_path", false, "PASS_PIC_PATH");
        public final static Property Distance_threshold = new Property(21, Integer.class, "distance_threshold", false, "DISTANCE_THRESHOLD");
        public final static Property Cities = new Property(22, String.class, "cities", false, "CITIES");
        public final static Property Interstitial = new Property(23, String.class, "interstitial", false, "INTERSTITIAL");
    };


    public PAppSettingsDao(DaoConfig config) {
        super(config);
    }
    
    public PAppSettingsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PAPP_SETTINGS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"IS_SECURE\" INTEGER," + // 1: is_secure
                "\"ADHOC_BASE_PATH\" TEXT," + // 2: adhoc_base_path
                "\"TEST_BASE_PATH\" TEXT," + // 3: test_base_path
                "\"STAGING_BASE_PATH\" TEXT," + // 4: staging_base_path
                "\"PROD_BASE_PATH\" TEXT," + // 5: prod_base_path
                "\"API_RESOURCE_PATH\" TEXT," + // 6: api_resource_path
                "\"ACTIVE_PATH\" INTEGER," + // 7: active_path
                "\"IS_APP_ACTIVE\" INTEGER," + // 8: is_app_active
                "\"IS_APP_NEEDS_UPDATE\" INTEGER," + // 9: is_app_needs_update
                "\"IS_PAYPAL_ACTIVE\" INTEGER," + // 10: is_paypal_active
                "\"IS_DRAGONPAY_ACTIVE\" INTEGER," + // 11: is_dragonpay_active
                "\"IS_GLOBELABS_ACTIVE\" INTEGER," + // 12: is_globelabs_active
                "\"WILL_FORCE_CLOSE_WHEN_CANCELLED_UPDATES\" INTEGER," + // 13: will_force_close_when_cancelled_updates
                "\"ALLOW_ADS\" INTEGER," + // 14: allow_ads
                "\"EVENT_MAIN_PICS_PATH\" TEXT," + // 15: event_main_pics_path
                "\"EVENT_BANNER_PICS_PATH\" TEXT," + // 16: event_banner_pics_path
                "\"VENUE_MAIN_PICS_PATH\" TEXT," + // 17: venue_main_pics_path
                "\"VENUE_BANNER_PICS_PATH\" TEXT," + // 18: venue_banner_pics_path
                "\"BOOTH_MAP_PATH\" TEXT," + // 19: booth_map_path
                "\"PASS_PIC_PATH\" TEXT," + // 20: pass_pic_path
                "\"DISTANCE_THRESHOLD\" INTEGER," + // 21: distance_threshold
                "\"CITIES\" TEXT," + // 22: cities
                "\"INTERSTITIAL\" TEXT);"); // 23: interstitial
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PAPP_SETTINGS\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, PAppSettings entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer is_secure = entity.getIs_secure();
        if (is_secure != null) {
            stmt.bindLong(2, is_secure);
        }
 
        String adhoc_base_path = entity.getAdhoc_base_path();
        if (adhoc_base_path != null) {
            stmt.bindString(3, adhoc_base_path);
        }
 
        String test_base_path = entity.getTest_base_path();
        if (test_base_path != null) {
            stmt.bindString(4, test_base_path);
        }
 
        String staging_base_path = entity.getStaging_base_path();
        if (staging_base_path != null) {
            stmt.bindString(5, staging_base_path);
        }
 
        String prod_base_path = entity.getProd_base_path();
        if (prod_base_path != null) {
            stmt.bindString(6, prod_base_path);
        }
 
        String api_resource_path = entity.getApi_resource_path();
        if (api_resource_path != null) {
            stmt.bindString(7, api_resource_path);
        }
 
        Integer active_path = entity.getActive_path();
        if (active_path != null) {
            stmt.bindLong(8, active_path);
        }
 
        Integer is_app_active = entity.getIs_app_active();
        if (is_app_active != null) {
            stmt.bindLong(9, is_app_active);
        }
 
        Integer is_app_needs_update = entity.getIs_app_needs_update();
        if (is_app_needs_update != null) {
            stmt.bindLong(10, is_app_needs_update);
        }
 
        Integer is_paypal_active = entity.getIs_paypal_active();
        if (is_paypal_active != null) {
            stmt.bindLong(11, is_paypal_active);
        }
 
        Integer is_dragonpay_active = entity.getIs_dragonpay_active();
        if (is_dragonpay_active != null) {
            stmt.bindLong(12, is_dragonpay_active);
        }
 
        Integer is_globelabs_active = entity.getIs_globelabs_active();
        if (is_globelabs_active != null) {
            stmt.bindLong(13, is_globelabs_active);
        }
 
        Integer will_force_close_when_cancelled_updates = entity.getWill_force_close_when_cancelled_updates();
        if (will_force_close_when_cancelled_updates != null) {
            stmt.bindLong(14, will_force_close_when_cancelled_updates);
        }
 
        Integer allow_ads = entity.getAllow_ads();
        if (allow_ads != null) {
            stmt.bindLong(15, allow_ads);
        }
 
        String event_main_pics_path = entity.getEvent_main_pics_path();
        if (event_main_pics_path != null) {
            stmt.bindString(16, event_main_pics_path);
        }
 
        String event_banner_pics_path = entity.getEvent_banner_pics_path();
        if (event_banner_pics_path != null) {
            stmt.bindString(17, event_banner_pics_path);
        }
 
        String venue_main_pics_path = entity.getVenue_main_pics_path();
        if (venue_main_pics_path != null) {
            stmt.bindString(18, venue_main_pics_path);
        }
 
        String venue_banner_pics_path = entity.getVenue_banner_pics_path();
        if (venue_banner_pics_path != null) {
            stmt.bindString(19, venue_banner_pics_path);
        }
 
        String booth_map_path = entity.getBooth_map_path();
        if (booth_map_path != null) {
            stmt.bindString(20, booth_map_path);
        }
 
        String pass_pic_path = entity.getPass_pic_path();
        if (pass_pic_path != null) {
            stmt.bindString(21, pass_pic_path);
        }
 
        Integer distance_threshold = entity.getDistance_threshold();
        if (distance_threshold != null) {
            stmt.bindLong(22, distance_threshold);
        }
 
        String cities = entity.getCities();
        if (cities != null) {
            stmt.bindString(23, cities);
        }
 
        String interstitial = entity.getInterstitial();
        if (interstitial != null) {
            stmt.bindString(24, interstitial);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public PAppSettings readEntity(Cursor cursor, int offset) {
        PAppSettings entity = new PAppSettings( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // is_secure
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // adhoc_base_path
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // test_base_path
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // staging_base_path
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // prod_base_path
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // api_resource_path
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // active_path
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8), // is_app_active
            cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9), // is_app_needs_update
            cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10), // is_paypal_active
            cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11), // is_dragonpay_active
            cursor.isNull(offset + 12) ? null : cursor.getInt(offset + 12), // is_globelabs_active
            cursor.isNull(offset + 13) ? null : cursor.getInt(offset + 13), // will_force_close_when_cancelled_updates
            cursor.isNull(offset + 14) ? null : cursor.getInt(offset + 14), // allow_ads
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // event_main_pics_path
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // event_banner_pics_path
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // venue_main_pics_path
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // venue_banner_pics_path
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // booth_map_path
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // pass_pic_path
            cursor.isNull(offset + 21) ? null : cursor.getInt(offset + 21), // distance_threshold
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // cities
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23) // interstitial
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, PAppSettings entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIs_secure(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setAdhoc_base_path(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTest_base_path(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setStaging_base_path(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setProd_base_path(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setApi_resource_path(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setActive_path(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setIs_app_active(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
        entity.setIs_app_needs_update(cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9));
        entity.setIs_paypal_active(cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10));
        entity.setIs_dragonpay_active(cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11));
        entity.setIs_globelabs_active(cursor.isNull(offset + 12) ? null : cursor.getInt(offset + 12));
        entity.setWill_force_close_when_cancelled_updates(cursor.isNull(offset + 13) ? null : cursor.getInt(offset + 13));
        entity.setAllow_ads(cursor.isNull(offset + 14) ? null : cursor.getInt(offset + 14));
        entity.setEvent_main_pics_path(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setEvent_banner_pics_path(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setVenue_main_pics_path(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setVenue_banner_pics_path(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setBooth_map_path(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setPass_pic_path(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setDistance_threshold(cursor.isNull(offset + 21) ? null : cursor.getInt(offset + 21));
        entity.setCities(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setInterstitial(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(PAppSettings entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(PAppSettings entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
