package com.akaiyuki.partyphile.passportapp.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.akaiyuki.partyphile.passportapp.dao.PEvents;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PEVENTS".
*/
public class PEventsDao extends AbstractDao<PEvents, Long> {

    public static final String TABLENAME = "PEVENTS";

    /**
     * Properties of entity PEvents.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Venue = new Property(2, String.class, "venue", false, "VENUE");
        public final static Property Event_datetime = new Property(3, String.class, "event_datetime", false, "EVENT_DATETIME");
        public final static Property Booth_map_img = new Property(4, String.class, "booth_map_img", false, "BOOTH_MAP_IMG");
        public final static Property Main_pic = new Property(5, String.class, "main_pic", false, "MAIN_PIC");
        public final static Property Banner_pic = new Property(6, String.class, "banner_pic", false, "BANNER_PIC");
        public final static Property Cutoff_datetime = new Property(7, String.class, "cutoff_datetime", false, "CUTOFF_DATETIME");
        public final static Property Priority = new Property(8, Integer.class, "priority", false, "PRIORITY");
        public final static Property Keywords = new Property(9, String.class, "keywords", false, "KEYWORDS");
        public final static Property Is_featured = new Property(10, Integer.class, "is_featured", false, "IS_FEATURED");
        public final static Property Is_exclusive = new Property(11, Integer.class, "is_exclusive", false, "IS_EXCLUSIVE");
        public final static Property Max_attendees = new Property(12, Integer.class, "max_attendees", false, "MAX_ATTENDEES");
        public final static Property Attendees_count = new Property(13, Integer.class, "attendees_count", false, "ATTENDEES_COUNT");
        public final static Property Longlitude = new Property(14, Double.class, "longlitude", false, "LONGLITUDE");
        public final static Property Latitude = new Property(15, Double.class, "latitude", false, "LATITUDE");
    };


    public PEventsDao(DaoConfig config) {
        super(config);
    }
    
    public PEventsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PEVENTS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"VENUE\" TEXT," + // 2: venue
                "\"EVENT_DATETIME\" TEXT," + // 3: event_datetime
                "\"BOOTH_MAP_IMG\" TEXT," + // 4: booth_map_img
                "\"MAIN_PIC\" TEXT," + // 5: main_pic
                "\"BANNER_PIC\" TEXT," + // 6: banner_pic
                "\"CUTOFF_DATETIME\" TEXT," + // 7: cutoff_datetime
                "\"PRIORITY\" INTEGER," + // 8: priority
                "\"KEYWORDS\" TEXT," + // 9: keywords
                "\"IS_FEATURED\" INTEGER," + // 10: is_featured
                "\"IS_EXCLUSIVE\" INTEGER," + // 11: is_exclusive
                "\"MAX_ATTENDEES\" INTEGER," + // 12: max_attendees
                "\"ATTENDEES_COUNT\" INTEGER," + // 13: attendees_count
                "\"LONGLITUDE\" REAL," + // 14: longlitude
                "\"LATITUDE\" REAL);"); // 15: latitude
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PEVENTS\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, PEvents entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String venue = entity.getVenue();
        if (venue != null) {
            stmt.bindString(3, venue);
        }
 
        String event_datetime = entity.getEvent_datetime();
        if (event_datetime != null) {
            stmt.bindString(4, event_datetime);
        }
 
        String booth_map_img = entity.getBooth_map_img();
        if (booth_map_img != null) {
            stmt.bindString(5, booth_map_img);
        }
 
        String main_pic = entity.getMain_pic();
        if (main_pic != null) {
            stmt.bindString(6, main_pic);
        }
 
        String banner_pic = entity.getBanner_pic();
        if (banner_pic != null) {
            stmt.bindString(7, banner_pic);
        }
 
        String cutoff_datetime = entity.getCutoff_datetime();
        if (cutoff_datetime != null) {
            stmt.bindString(8, cutoff_datetime);
        }
 
        Integer priority = entity.getPriority();
        if (priority != null) {
            stmt.bindLong(9, priority);
        }
 
        String keywords = entity.getKeywords();
        if (keywords != null) {
            stmt.bindString(10, keywords);
        }
 
        Integer is_featured = entity.getIs_featured();
        if (is_featured != null) {
            stmt.bindLong(11, is_featured);
        }
 
        Integer is_exclusive = entity.getIs_exclusive();
        if (is_exclusive != null) {
            stmt.bindLong(12, is_exclusive);
        }
 
        Integer max_attendees = entity.getMax_attendees();
        if (max_attendees != null) {
            stmt.bindLong(13, max_attendees);
        }
 
        Integer attendees_count = entity.getAttendees_count();
        if (attendees_count != null) {
            stmt.bindLong(14, attendees_count);
        }
 
        Double longlitude = entity.getLonglitude();
        if (longlitude != null) {
            stmt.bindDouble(15, longlitude);
        }
 
        Double latitude = entity.getLatitude();
        if (latitude != null) {
            stmt.bindDouble(16, latitude);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public PEvents readEntity(Cursor cursor, int offset) {
        PEvents entity = new PEvents( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // venue
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // event_datetime
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // booth_map_img
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // main_pic
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // banner_pic
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // cutoff_datetime
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8), // priority
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // keywords
            cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10), // is_featured
            cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11), // is_exclusive
            cursor.isNull(offset + 12) ? null : cursor.getInt(offset + 12), // max_attendees
            cursor.isNull(offset + 13) ? null : cursor.getInt(offset + 13), // attendees_count
            cursor.isNull(offset + 14) ? null : cursor.getDouble(offset + 14), // longlitude
            cursor.isNull(offset + 15) ? null : cursor.getDouble(offset + 15) // latitude
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, PEvents entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setVenue(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setEvent_datetime(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setBooth_map_img(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setMain_pic(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setBanner_pic(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setCutoff_datetime(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setPriority(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
        entity.setKeywords(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setIs_featured(cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10));
        entity.setIs_exclusive(cursor.isNull(offset + 11) ? null : cursor.getInt(offset + 11));
        entity.setMax_attendees(cursor.isNull(offset + 12) ? null : cursor.getInt(offset + 12));
        entity.setAttendees_count(cursor.isNull(offset + 13) ? null : cursor.getInt(offset + 13));
        entity.setLonglitude(cursor.isNull(offset + 14) ? null : cursor.getDouble(offset + 14));
        entity.setLatitude(cursor.isNull(offset + 15) ? null : cursor.getDouble(offset + 15));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(PEvents entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(PEvents entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
