package com.akaiyuki.partyphile.passportapp.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.akaiyuki.partyphile.passportapp.dao.PEvents;
import com.akaiyuki.partyphile.passportapp.dao.PAppSettings;

import com.akaiyuki.partyphile.passportapp.dao.PEventsDao;
import com.akaiyuki.partyphile.passportapp.dao.PAppSettingsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig pEventsDaoConfig;
    private final DaoConfig pAppSettingsDaoConfig;

    private final PEventsDao pEventsDao;
    private final PAppSettingsDao pAppSettingsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        pEventsDaoConfig = daoConfigMap.get(PEventsDao.class).clone();
        pEventsDaoConfig.initIdentityScope(type);

        pAppSettingsDaoConfig = daoConfigMap.get(PAppSettingsDao.class).clone();
        pAppSettingsDaoConfig.initIdentityScope(type);

        pEventsDao = new PEventsDao(pEventsDaoConfig, this);
        pAppSettingsDao = new PAppSettingsDao(pAppSettingsDaoConfig, this);

        registerDao(PEvents.class, pEventsDao);
        registerDao(PAppSettings.class, pAppSettingsDao);
    }
    
    public void clear() {
        pEventsDaoConfig.getIdentityScope().clear();
        pAppSettingsDaoConfig.getIdentityScope().clear();
    }

    public PEventsDao getPEventsDao() {
        return pEventsDao;
    }

    public PAppSettingsDao getPAppSettingsDao() {
        return pAppSettingsDao;
    }

}
