package com.akaiyuki.partyphile.passportapp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PEVENTS".
 */
public class PEvents {

    private Long id;
    private Boolean archived;
    private java.util.Date dateUpdated;
    private Integer groupOrder;
    private String name;
    private Integer sortOrder;
    private String tags;
    private String timeStamp;
    private Long pid;
    private String Eventname;
    private String venue;
    private String event_datetime;
    private String booth_map_img;
    private String main_pic;
    private String banner_pic;
    private String cutoff_datetime;
    private Integer priority;
    private String keywords;
    private Integer is_featured;
    private Integer is_exclusive;
    private Integer max_attendees;
    private Integer attendees_count;
    private Double longlitude;
    private Double latitude;

    public PEvents() {
    }

    public PEvents(Long id) {
        this.id = id;
    }

    public PEvents(Long id, Boolean archived, java.util.Date dateUpdated, Integer groupOrder, String name, Integer sortOrder, String tags, String timeStamp, Long pid, String Eventname, String venue, String event_datetime, String booth_map_img, String main_pic, String banner_pic, String cutoff_datetime, Integer priority, String keywords, Integer is_featured, Integer is_exclusive, Integer max_attendees, Integer attendees_count, Double longlitude, Double latitude) {
        this.id = id;
        this.archived = archived;
        this.dateUpdated = dateUpdated;
        this.groupOrder = groupOrder;
        this.name = name;
        this.sortOrder = sortOrder;
        this.tags = tags;
        this.timeStamp = timeStamp;
        this.pid = pid;
        this.Eventname = Eventname;
        this.venue = venue;
        this.event_datetime = event_datetime;
        this.booth_map_img = booth_map_img;
        this.main_pic = main_pic;
        this.banner_pic = banner_pic;
        this.cutoff_datetime = cutoff_datetime;
        this.priority = priority;
        this.keywords = keywords;
        this.is_featured = is_featured;
        this.is_exclusive = is_exclusive;
        this.max_attendees = max_attendees;
        this.attendees_count = attendees_count;
        this.longlitude = longlitude;
        this.latitude = latitude;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean getArchived() {
        return archived;
    }

    public void setArchived(Boolean archived) {
        this.archived = archived;
    }

    public java.util.Date getDateUpdated() {
        return dateUpdated;
    }

    public void setDateUpdated(java.util.Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }

    public Integer getGroupOrder() {
        return groupOrder;
    }

    public void setGroupOrder(Integer groupOrder) {
        this.groupOrder = groupOrder;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getSortOrder() {
        return sortOrder;
    }

    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    public String getTags() {
        return tags;
    }

    public void setTags(String tags) {
        this.tags = tags;
    }

    public String getTimeStamp() {
        return timeStamp;
    }

    public void setTimeStamp(String timeStamp) {
        this.timeStamp = timeStamp;
    }

    public Long getPid() {
        return pid;
    }

    public void setPid(Long pid) {
        this.pid = pid;
    }

    public String getEventname() {
        return Eventname;
    }

    public void setEventname(String Eventname) {
        this.Eventname = Eventname;
    }

    public String getVenue() {
        return venue;
    }

    public void setVenue(String venue) {
        this.venue = venue;
    }

    public String getEvent_datetime() {
        return event_datetime;
    }

    public void setEvent_datetime(String event_datetime) {
        this.event_datetime = event_datetime;
    }

    public String getBooth_map_img() {
        return booth_map_img;
    }

    public void setBooth_map_img(String booth_map_img) {
        this.booth_map_img = booth_map_img;
    }

    public String getMain_pic() {
        return main_pic;
    }

    public void setMain_pic(String main_pic) {
        this.main_pic = main_pic;
    }

    public String getBanner_pic() {
        return banner_pic;
    }

    public void setBanner_pic(String banner_pic) {
        this.banner_pic = banner_pic;
    }

    public String getCutoff_datetime() {
        return cutoff_datetime;
    }

    public void setCutoff_datetime(String cutoff_datetime) {
        this.cutoff_datetime = cutoff_datetime;
    }

    public Integer getPriority() {
        return priority;
    }

    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    public String getKeywords() {
        return keywords;
    }

    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }

    public Integer getIs_featured() {
        return is_featured;
    }

    public void setIs_featured(Integer is_featured) {
        this.is_featured = is_featured;
    }

    public Integer getIs_exclusive() {
        return is_exclusive;
    }

    public void setIs_exclusive(Integer is_exclusive) {
        this.is_exclusive = is_exclusive;
    }

    public Integer getMax_attendees() {
        return max_attendees;
    }

    public void setMax_attendees(Integer max_attendees) {
        this.max_attendees = max_attendees;
    }

    public Integer getAttendees_count() {
        return attendees_count;
    }

    public void setAttendees_count(Integer attendees_count) {
        this.attendees_count = attendees_count;
    }

    public Double getLonglitude() {
        return longlitude;
    }

    public void setLonglitude(Double longlitude) {
        this.longlitude = longlitude;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

}
